apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-amjr
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0042-tenant/tkrw-pr714-0075-0042-app/devfile-sample-amjr@sha256:91ec8e17db68f090c96086f2de81e034cdd9301fecdc445a85fc986d464d9fe6
        name: my-nodejs
        resources: {}
status: {}
